### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by jzabroski**

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

Thank you for the pull request but I'm not sure which broken link that fix?

Instead of pointing to the page on `http://entityframework.net`, you point directly to the repository.

Best Regards,

Jonathan

**Comment by jzabroski** [comment]
When I navigate to https://github.com/zzzprojects/EntityFramework-FAQ/blob/master/docs2/pages/thirdpartylibraries/third-party-libraries.md all page links are broken.

**Comment by JonathanMagnan** [comment]
That's because this is a site web ;)

We could probably review the code to make it work in both (GitHub and Website)

See here: http://entityframework.net/third-party-libraries

**Comment by jzabroski** [comment]
Ah!

Yes, that would be good and helps me to understand what those projects refer to.

How are you generating a website from markdown files?  I take it you aren't using GitHub markdown?

**Comment by JonathanMagnan** [comment]
We were previously using GitHub Pages (https://pages.github.com/)

But we recently moved our websites into an `MVC` project to make it easier to make global layout changes.

So we mostly read the raw text of the file in the MVC project: https://raw.githubusercontent.com/zzzprojects/EntityFramework-FAQ/master/docs2/pages/thirdpartylibraries/third-party-libraries.md and use https://www.nuget.org/packages/Markdig/

We made every week some improvments.

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

I will close this pull. If you have some question, feel free to contact us: info@zzzprojects.com

Best Regards,

Jonathan

**Pull request closed without merging**
